[package]
name = "qmk-hid-host"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
hidapi = "2.4.0"

[dependencies.async-std]
version = "1.12.0"
features = ["attributes"]

[dependencies.windows]
version = "0.48"
features = [
    "Foundation",
    "Media",
    "Media_Control",
    "Globalization",
    "Win32_Globalization",
    "Win32_Foundation",
    "Win32_UI_TextServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
]
